# Generated by Django 5.1.5 on 2025-02-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_cartmodel_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(to='testapp.productmodel'),
        ),
    ]
